mysql:
  image: openzipkin/zipkin-mysql:1.38.0
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-java:0.9.1
  environment:
    - STORAGE_TYPE=mysql
  ports:
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8080:9411
  links:
    - mysql:storage
