server:
  port: 9411

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://${MYSQL_HOST:localhost}/test
    username: root
    password: root
# Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
zipkin:
  store:
    type: mysql # default is inMemory

---
spring:
  profiles: test
  datasource:
    initialize: false
zipkin:
  store:
    type: mem # default is inMemory
