server:
  port: 9411

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  datasource:
    initialize: false

zipkin:
  collector:
    sample-rate: 1.0 # percentage to traces to retain
  query:
    lookback: 86400000 # 7 days in millis
  store:
    type: mem # default is inMemory

---
spring:
  profiles: mysql
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://${MYSQL_HOST:localhost}/test
    username: root
    password: root
# Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
zipkin:
  store:
    type: mysql # default is inMemory
